<fizzbuzz.py>

def fizzbuzz(num):
    """
    引数が3の倍数なら'Fizz'、5の倍数なら'Buzz'、両方の倍数なら'FizzBuzz'を返す。
    いずれの倍数でもない場合は受け取った数値をそのまま返す。
    """

    if num % 3 == 0 and num % 5 == 0:
        return 'FizzBuzz'

    if num % 3 == 0:
        return 'Fizz'

    if num % 5 == 0:
        return 'Buzz'

    return num


=====================================================
<test_fizzbuzz.py>

import unittest
import fizzbuzz

class TestFizzBuzz(unittest.TestCase):

    def test_fizz(self):
        self.assertEqual('Fizz', fizzbuzz.fizzbuzz(3))

    def test_buzz(self):
        self.assertEqual('Buzz', fizzbuzz.fizzbuzz(5))


=====================================================
<.github/workflows/python-test-workflow.yml>

name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Lint
        run: |
          flake8 . --count --show-source --statistics --exclude=./test_*.py
      - name: Test
        run: |
          pytest test_*.py
